### ISSUE TITLE
Error in HashPassword() method?

### ISSUE THREAD

**Issue by bdemarzo** [roadkillwiki/roadkill#11]
I was looking at the code to see how I can integrate the wiki with an existing application, and came across the following in User.cs, line 138:

byte[] hash = sha.ComputeHash(Encoding.ASCII.GetBytes(password + "salt"));

Should the salt at the end be the parameter and not a string named "salt"? e.g.:

byte[] hash = sha.ComputeHash(Encoding.ASCII.GetBytes(password + salt));

**Comment by 304NotModified** [comment]
Sounds like a major security bug!

**Comment by yetanotherchris** [comment]
It definitely needs fixing (I'm going to fix it on main today), however the typo is **only if you are not using `FormsAuthentication`**. 

I'm not sure what the scenario for this would be, the code was there primarily for aiding in testing the `UserService`. The test coverage sucks for this area though, so that's another aspect I'll look into.

So in short - don't panic your passwords are definitely salted with a random salt!

**Comment by 304NotModified** [comment]
This is fixed isn't it?

**Comment by yetanotherchris** [comment]
@304NotModified thanks, closed it

**Comment by yetanotherchris** [comment]
Fixed in e7b8ff75a3408f7c028f13fbe0e0c1fd6c59bbb5
