### ISSUE TITLE
Performance problem on tag pages

### ISSUE THREAD

**Issue by 304NotModified** [roadkillwiki/roadkill#17]
Hi,

We are happy with Roadkill (and certainly the new roadmap), but we have some small performance issues.

A page view takes sometimes 4 seconds. As experienced web application developers, we find that surprising, as we build a lot of applications with live data with thousand records in less then a half second . (of course not showing all the thousand records at once) - (no bragging intended)

Are there any things that we could speed things up? The hardware should not be a problem (dedicated hardware, 16GB ram, 4 CPU's).

We have now 95 pages. After first load of a page, that page it's fast (700 ms)

One thing I have noticed, this one is called a lot (cold boot after app pool recycle, 1 page, a tag page)
```
SELECT
  roadkill_siteconfiguration.Id AS [roadkill_siteconfiguration.Id],
  roadkill_siteconfiguration.content AS [roadkill_siteconfiguration.content],
  roadkill_siteconfiguration.version AS [roadkill_siteconfiguration.version]
FROM
  roadkill_siteconfiguration
```
~ 60 times for one page!

![image](https://cloud.githubusercontent.com/assets/5808377/8862076/4865bfd2-318e-11e5-8ad5-9c0296fa6ca9.png)

- We use the lasted (released) version. 
- Windows server 2008 R2, SQL server 2008 R2
- AD integration

**Comment by 304NotModified** [comment]
Most pages calls the same query, 20-30 times. A tag page with 15 pages ~60

**Comment by yetanotherchris** [comment]
Sorry about the delay in responding to this, 6 months later - hopefully you're still using Roadkill  :pray: 

The problem was the way the repository was using Lightspeed, it doesn't use the first level cache for LINQ statements, so it just kept calling the database (Roadkill assumes the repository looks after caching and doesn't care how many times the repository is called).

Hopefully this fix speeds it up. I also noticed the Structuremap usage is also far from optimal so a version 3 will be needed for that.

**Comment by 304NotModified** [comment]
OK, thanks for the reply. We still use Roadkill, but I have to admit that we would use it more if the performance was more acceptable (people are complaining about it :( ) .

**Comment by 304NotModified** [comment]
I like to test this, see https://gitter.im/roadkillwiki/general
