### ISSUE TITLE
Is there a version 3.0 coming out?

### ISSUE THREAD

**Issue by thenrich2009** [roadkillwiki/roadkill#53]
Is there a version 3.0 coming out? A few months ago you (Chris) said you're busy working on another FOSS project. Should we expect a version 3.0 sometime this year?

**Comment by iAlexanderMoon** [comment]
Is there a version 3.0 repository that can be hacked on?

**Comment by yetanotherchris** [comment]
Version 3 probably won't be out this year, but it has been started. The emphasis for version 3 is .NET core on Docker, so that updates to Roadkill can be done effortless. Right now updates are a complete pain, particularly any settings migration.

To migrate to version 3 I need to convert a few of the dependencies over to newer libraries:

- HtmlSanitizer (done)
- MongoDB (trivial)
- Remove Lightspeed, move to Repositories with SQL inside (done)
- Remove Creole (In progress)
- Move from MarkdownSharp to Markdig (in progress)
- Lucene.net (todo)

Once these are done, it's then a case of converting the projects to xproj and project.json which should be fairly straightforward. There's probably going to be Microsoft tooling for this in the new year though, which will make it even easier.

There's going to be no new versions until version 3 - so master is being used for these new changes. If you need the last version 2.x there's still a tag for that.

Once version 3 is out, master will be stable and Roadkill will move to feature-branches.
